// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFpfrDY6zfe8qapRsuEp1dZXDzDKRcPA',
    appId: '1:413226749154:android:150a48cfb433f440d162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    storageBucket: 'roombookingapp-da5df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg71rA6v8ZlZJqxZOeVK2negbqrQfrrNw',
    appId: '1:413226749154:ios:039ee1972dc04181d162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    storageBucket: 'roombookingapp-da5df.appspot.com',
    androidClientId: '413226749154-49fclsip7eo39t5m59nphc7jd5tqk7v7.apps.googleusercontent.com',
    iosClientId: '413226749154-6k9niq7i0la0n3545rsjvcmtetmjg3hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_AKhzEDUBsrBd5p6A-kRzdwBSivakcY',
    appId: '1:413226749154:web:28645def39fd1130d162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    authDomain: 'roombookingapp-da5df.firebaseapp.com',
    storageBucket: 'roombookingapp-da5df.appspot.com',
    measurementId: 'G-KVKL25N0EB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg71rA6v8ZlZJqxZOeVK2negbqrQfrrNw',
    appId: '1:413226749154:ios:039ee1972dc04181d162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    storageBucket: 'roombookingapp-da5df.appspot.com',
    androidClientId: '413226749154-49fclsip7eo39t5m59nphc7jd5tqk7v7.apps.googleusercontent.com',
    iosClientId: '413226749154-6k9niq7i0la0n3545rsjvcmtetmjg3hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxs7CDKok9A8UiqQOPVgIusytTVU-Emw',
    appId: '1:413226749154:web:29732f3acceb949ad162bb',
    messagingSenderId: '413226749154',
    projectId: 'roombookingapp-da5df',
    authDomain: 'roombookingapp-da5df.firebaseapp.com',
    storageBucket: 'roombookingapp-da5df.appspot.com',
    measurementId: 'G-87F1W28WG5',
  );

}